name: Update arXiv Papers

on:
  schedule:
    # Run at 00:00 on the 1st day of every month
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch: # Allows you to run it manually anytime

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Fetch and Merge arXiv Feed
        run: node .github/scripts/merge_arxiv.js

      - name: Commit and Push if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add public/papers.xml
          # Only commit if the file has changed
          git commit -m "Auto-update arXiv papers" || exit 0
          git push
